export const ADD_CONTACT = 'ADD_CONTACT';
export const FIND_CONTACT = 'FIND_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const CURRENT_CONTACT = 'CURRENT_CONTACT';
export const CLEAR_CURRENT_CONTACT = 'CLEAR_CURRENT_CONTACT';
